apiVersion: v1
kind: Secret
metadata:
  name: training-secret
#  labels:
#    helm.sh/chart: aws-multi-ecr-credentials-1.4.3
#    app.kubernetes.io/instance: aws-ecr-creds-novisign
#    app.kubernetes.io/version: "1.4.3"
#    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
#  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID} #for helm
  #R2DBC
  r2dbc-password: "credentials"
  r2dbc-username: "credentials"
  r2dbc-url: "r2dbc:postgresql://postgres-service:5432/training"
  #MINIO
  minio-bucket: "bucketdefault"
  minio-username: "minio_user"
  minio-password: "minio_password"
  minio-url: "http://minio-service:9000"
  #MONGO
  mongo-db: "mongodb"
  mongo-port: "27017"
  mongo-host: "mongo-service"
  mongo-password: "mongo_password"
  #REDIS
  redis-port: "6379"
  redis-host: "redis-service"
  redis-password: "SuperSecretRedisPassword"
